---
development:
  cloud_name: dzcon8dw0
  api_key: '773413745382698'
  api_secret: yNbzbpiNUvI-LIVcqVhGBBgaoxs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dzcon8dw0
  api_key: '773413745382698'
  api_secret: yNbzbpiNUvI-LIVcqVhGBBgaoxs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dzcon8dw0
  api_key: '773413745382698'
  api_secret: yNbzbpiNUvI-LIVcqVhGBBgaoxs
  enhance_image_tag: true
  static_image_support: false
