default: &default
  adapter: mysql2
  username: root
  password: Gracias1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rspp_development

test:
  <<: *default
  database: rspp_test

production:
  adapter: mysql2
  database: rspp_production
  username: root
  password: Gracias1
